# Generated by Django 3.0.4 on 2020-04-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appburger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hamburgesa',
            new_name='Hamburguesa',
        ),
    ]
