# Generated by Django 3.0.4 on 2020-04-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appburger', '0002_auto_20200427_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
